"""Multi-tenant foundation: add business_id to Customer, Appointment, ProcessedMessage, ConversationHistory.

Revision ID: 0001
Revises: None (initial)
Create Date: 2026-06-15
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── Step 1: Add nullable business_id columns ──
    op.add_column("customers", sa.Column("business_id", sa.Integer(), nullable=True))
    op.add_column("appointments", sa.Column("business_id", sa.Integer(), nullable=True))
    op.add_column("processed_messages", sa.Column("business_id", sa.Integer(), nullable=True))
    op.add_column("conversation_history", sa.Column("business_id", sa.Integer(), nullable=True))

    # ── Step 2: Backfill business_id ──
    # Appointment: resolve via Barber.business_id
    op.execute(
        """
        UPDATE appointments
        SET business_id = (
            SELECT barbers.business_id
            FROM barbers
            WHERE barbers.id = appointments.barber_id
        )
        WHERE appointments.barber_id IS NOT NULL
    """
    )

    # Customer: use a reasonable default (e.g., first business) if no relation exists
    op.execute(
        """
        UPDATE customers
        SET business_id = (
            SELECT MIN(barbers.business_id)
            FROM barbers
            INNER JOIN appointments ON appointments.barber_id = barbers.id
            WHERE appointments.customer_id = customers.id
        )
    """
    )
    # Customers without appointments fall back to first business
    op.execute(
        """
        UPDATE customers
        SET business_id = (SELECT MIN(id) FROM businesses)
        WHERE business_id IS NULL
    """
    )

    # ConversationHistory: resolve via Customer.business_id
    op.execute(
        """
        UPDATE conversation_history
        SET business_id = (
            SELECT customers.business_id
            FROM customers
            WHERE customers.id = conversation_history.customer_id
        )
        WHERE conversation_history.customer_id IS NOT NULL
    """
    )

    # ProcessedMessage: fall back to first business
    op.execute(
        """
        UPDATE processed_messages
        SET business_id = (SELECT MIN(id) FROM businesses)
        WHERE business_id IS NULL
    """
    )

    # ── Step 3: Add NOT NULL constraints ──
    op.alter_column("customers", "business_id", nullable=False)
    op.alter_column("appointments", "business_id", nullable=False)
    op.alter_column("processed_messages", "business_id", nullable=False)
    op.alter_column("conversation_history", "business_id", nullable=False)

    # ── Step 4: Drop old single-column unique constraints ──
    # Customer phone_hash unique was autogenerated; drop it if it exists
    with op.batch_alter_table("customers") as batch_op:
        try:
            batch_op.drop_constraint("uq_customers_phone_hash", type_="unique")
        except Exception:
            pass  # Constraint may not exist

    # ProcessedMessage message_id unique was autogenerated; drop it if it exists
    with op.batch_alter_table("processed_messages") as batch_op:
        try:
            batch_op.drop_constraint("uq_processed_messages_message_id", type_="unique")
        except Exception:
            pass  # Constraint may not exist

    # ── Step 5: Add Foreign Keys ──
    op.create_foreign_key("fk_customers_business", "customers", "businesses", ["business_id"], ["id"])
    op.create_foreign_key("fk_appointments_business", "appointments", "businesses", ["business_id"], ["id"])
    op.create_foreign_key("fk_processed_messages_business", "processed_messages", "businesses", ["business_id"], ["id"])
    op.create_foreign_key(
        "fk_conversation_history_business", "conversation_history", "businesses", ["business_id"], ["id"]
    )

    # ── Step 6: Add composite unique constraints ──
    op.create_unique_constraint("uq_customer_phone_business", "customers", ["phone_hash", "business_id"])
    op.create_unique_constraint("uq_processed_msg_business", "processed_messages", ["message_id", "business_id"])


def downgrade() -> None:
    # ── Reverse Step 6: Drop composite unique constraints ──
    op.drop_constraint("uq_customer_phone_business", "customers", type_="unique")
    op.drop_constraint("uq_processed_msg_business", "processed_messages", type_="unique")

    # ── Reverse Step 5: Drop Foreign Keys ──
    op.drop_constraint("fk_customers_business", "customers", type_="foreignkey")
    op.drop_constraint("fk_appointments_business", "appointments", type_="foreignkey")
    op.drop_constraint("fk_processed_messages_business", "processed_messages", type_="foreignkey")
    op.drop_constraint("fk_conversation_history_business", "conversation_history", type_="foreignkey")

    # ── Reverse Step 1: Drop business_id columns ──
    op.drop_column("conversation_history", "business_id")
    op.drop_column("processed_messages", "business_id")
    op.drop_column("appointments", "business_id")
    op.drop_column("customers", "business_id")
